default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres # Usuario de PostgreSQL
  password: tu_contraseña # Contraseña de PostgreSQL
  host: localhost

development:
  <<: *default
  database: finanzas_api_development

test:
  <<: *default
  database: finanzas_api_test

production:
  <<: *default
  database: finanzas_api_production
  username: finanzas_api
  password: <%= ENV['FINANZAS_API_DATABASE_PASSWORD'] %>